_target_: src.model.HiFiGan
generator:
  in_channels: 80
  hidden_size: 512
  kernels_upsample: [16, 16, 4, 4]
  kernel_sizes: [3, 7, 11]
  dilations: [
            [[1, 1], [3, 1], [5, 1]],
            [[1, 1], [3, 1], [5, 1]],
            [[1, 1], [3, 1], [5, 1]],
        ]
mpd:
  periods: [2, 3, 5, 7, 11]
msd:
  n_channels: [1, 128, 128, 256, 512, 1024, 1024, 1024]
  kernel_sizes: [15, 41, 41, 41, 41, 41, 5]
  strides: [1, 2, 2, 4, 4, 1, 1]
  groups: [1, 4, 16, 16, 16, 16, 1]
