_target_: src.logger.WandBWriter
project_name: "HiFiGan"
entity: null
run_name: "base"
mode: "online"
loss_names: ["mel_spec_loss", "generator_loss", "msd_loss", "mpd_loss", "disc_loss", "feature_matching_loss", "generator_adv_loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
